version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: tamago_production
    volumes:
      - ./data/db:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    volumes:
      - ./data/redis:/data

  web:
    build: ./backend
    command: bash -c "bundle exec rails db:migrate && bundle exec puma -C config/puma.rb"
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://appuser:strongpassword@db/tamago_production
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY_BASE: ace4bec54c21a62b0bb292d081412db6ce49dac2ef4462df8a14288cc2aa52cb02e515ec0ce6119fb6463b1e7ec43eb79d63ac5b1dda31186d8414850d4a94a2
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    depends_on:
      - web

  nginx:
    image: nginx:alpine
    depends_on:
      - web
      - frontend
    ports:
      - "80:80"
      - "443:443"  # UNCOMMENT untuk HTTPS
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./frontend/build:/usr/share/nginx/html
      - ./certbot/conf:/etc/letsencrypt  # UNCOMMENT
      - ./certbot/www:/var/www/certbot   # UNCOMMENT

  certbot:  # UNCOMMENT SERVICE CERTBOT
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: echo "Certbot service - run manually for certificate issuance"