version: "3.9"

services:
  web:
    build: .
    container_name: rails_web
    command: bash -c "bundle exec rails db:prepare && bundle exec rails s -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/chat_app
      REDIS_URL: redis://redis:6379/1
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: rails_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_app
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: rails_redis
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"

volumes:
  pgdata:
  redisdata:
