version = 5.1.0
archive_dir = /etc/letsencrypt/archive/tamago.web.id
cert = /etc/letsencrypt/live/tamago.web.id/cert.pem
privkey = /etc/letsencrypt/live/tamago.web.id/privkey.pem
chain = /etc/letsencrypt/live/tamago.web.id/chain.pem
fullchain = /etc/letsencrypt/live/tamago.web.id/fullchain.pem
[renewalparams]
account = 935f1b4a30991cf4ba7a0acd5737deee
pref_challs = http-01,
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[acme_renewal_info]
ari_retry_after = 2025-10-28T16:19:05
